project_id = "jwulacyvagxztjopbflh"

[functions.webhook-dispatcher]
verify_jwt = false

[functions.n8n-api-caller]
verify_jwt = false

[functions.document-processor]
verify_jwt = false

[functions.metrics-aggregator]
verify_jwt = false

[functions.incident-monitor]
verify_jwt = false
[functions.create-user]
enabled = true
verify_jwt = true
import_map = "./functions/create-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-user/*.html" ]
